---
- name: DISCOVER IOS VERSION 
  hosts: csr
  gather_facts: False
  connection: local
 
  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show interfaces
      register: ios_version_output
   
    - name: Configure logging buffer size
      ios_config:
        lines:
          - logging buffered 5000
      become: yes
      become_method: enable

    - name: save output to file
      copy:
        content: "{{ ios_version_output['stdout'][0]}}"
        dest: ios_version_output.txt

